// ClawPark Discord Coordinator Bot.
// All responses are generated by LLM (OpenRouter). No hardcoded user-facing messages.
// Trigger: @ClawPark mention OR !breed prefix.

import { Client, Events, GatewayIntentBits, type Message } from 'discord.js';
import type { OrchestratorDeps, RequesterIdentity } from '../src/types/breedingIntent.ts';
import { access, writeFile, mkdir, rm } from 'node:fs/promises';
import { homedir, tmpdir } from 'node:os';
import { isAbsolute, join, resolve, sep } from 'node:path';
import { randomUUID } from 'node:crypto';
import { parseDiscordMessage, stripBotPrefix } from './discordIntent.ts';
import { createOpenRouterClient } from './openrouter.ts';
import {
  cancelIntent,
  checkEligibilityAndConsent,
  createIntent,
  executeBreed,
  getUserLastIntent,
  markIntentSaved,
  setUserLastIntent,
  suggestCandidates,
} from './breedingOrchestrator.ts';

export interface DiscordBotDeps {
  token: string;
  orchestratorDeps: OrchestratorDeps;
  importSpecimen?: (zipPath: string, discordUserId: string) => Promise<{ specimenName: string; specimenId: string }>;
  allowLocalZipPathImport?: boolean;
}

interface MentionedUser {
  id: string;
  displayName: string;
}

type CandidateReplyMode = 'available-specimens' | 'partner-options';

const PERSUADE_MEMORY_MS = 15 * 60 * 1000;
const persuadeMemory = new Map<string, { targets: MentionedUser[]; updatedAt: number }>();

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export function containsPlainBotReference(message: string, names: string[]) {
  const normalizedNames = names.map((name) => name.trim()).filter(Boolean);
  return normalizedNames.some((name) => {
    const pattern = new RegExp(`(^|\\s)@?${escapeRegExp(name)}(?=\\s|$|[.!?,:;])`, 'i');
    return pattern.test(message);
  });
}

export function isLikelyPersuadeFollowUp(message: string) {
  return /this guy|do again|again|keep continuing|continue|check above|above zip|same guy|same user|retry|한번 더|다시/i.test(message);
}

export function isSpecimenInventoryQuestion(message: string) {
  return /what claws|what specimens|name all|list all|show all|available claws|available specimens|what do you have|how many claws|which claws|specimen details/i.test(message.toLowerCase());
}

export function extractLocalZipPath(message: string) {
  const match = message.match(/((?:\/|~\/|\.\/)[^\s"'`]+\.zip)\b/i);
  return match?.[1] ?? null;
}

function normalizeLocalZipPath(zipPath: string, cwd = process.cwd()) {
  if (zipPath.startsWith('~/')) {
    return resolve(homedir(), zipPath.slice(2));
  }
  return isAbsolute(zipPath) ? resolve(zipPath) : resolve(cwd, zipPath);
}

export function isAllowedLocalZipPath(zipPath: string, cwd = process.cwd()) {
  const normalized = normalizeLocalZipPath(zipPath, cwd);
  const allowedRoots = [resolve(tmpdir()), resolve('/tmp'), resolve(cwd)];
  return normalized.toLowerCase().endsWith('.zip')
    && allowedRoots.some((root) => normalized === root || normalized.startsWith(`${root}${sep}`));
}

function rememberPersuadeTargets(authorId: string, targets: MentionedUser[]) {
  if (targets.length === 0) return;
  persuadeMemory.set(authorId, { targets, updatedAt: Date.now() });
}

function getRememberedPersuadeTargets(authorId: string) {
  const memory = persuadeMemory.get(authorId);
  if (!memory) return [];
  if (Date.now() - memory.updatedAt > PERSUADE_MEMORY_MS) {
    persuadeMemory.delete(authorId);
    return [];
  }
  return memory.targets;
}

export function resolvePersuadeTargets(currentTargets: MentionedUser[], rememberedTargets: MentionedUser[], message: string) {
  if (currentTargets.length > 0) return currentTargets;
  if (isLikelyPersuadeFollowUp(message)) return rememberedTargets;
  return [];
}

export function displayCandidateName(candidate: { name?: string; specimenId: string }) {
  const name = candidate.name?.trim();
  return name && name.length > 0 ? name : candidate.specimenId;
}

export function formatCandidateSuggestionsReply(
  candidates: Array<{ specimenId: string; name?: string; compatibilitySummary: string; eligibleForAutoApprove: boolean }>,
  mode: CandidateReplyMode,
  targetName?: string,
) {
  if (candidates.length === 0) {
    return 'I do not currently see any breedable claws in the park. Upload or claim a specimen first, then try again.';
  }

  const lines = candidates.map((candidate, index) => {
    const label = displayCandidateName(candidate);
    return `${index + 1}. **${label}** — ${candidate.compatibilitySummary} (${candidate.eligibleForAutoApprove ? 'auto-approve eligible' : 'mutual approval required'})`;
  });

  if (mode === 'available-specimens') {
    return [
      'Here are the claws currently available to breed:',
      '',
      ...lines,
      '',
      'Reply with **two specimen names** to start breeding, for example: `breed Ridgeback with Orchid Glass`.',
    ].join('\n');
  }

  return [
    `Here are the available breeding partners${targetName ? ` for **${targetName}**` : ''}:`,
    '',
    ...lines,
    '',
    'You can say **"proceed"** to use the first option, or reply with a specific specimen name.',
  ].join('\n');
}

// --- LLM response generator ---

const RESPONSE_SYSTEM_PROMPT = `You are ClawPark Bot, a friendly Discord assistant for an OpenClaw agent breeding system.
You help users breed AI agents, discover breeding partners, and track lineage.

Rules:
- Be concise (1-3 short paragraphs max for Discord readability)
- Use Discord markdown (bold, code blocks, bullet points)
- Be warm and helpful, like a knowledgeable lab assistant
- If you have specimen data, mention names naturally
- Use emoji sparingly but appropriately
- Support both English and Korean naturally
- Never mention internal implementation details (API endpoints, JSON, etc.)
- When showing candidates, format as a numbered list with names`;

async function generateResponse(context: string): Promise<string> {
  try {
    const client = createOpenRouterClient();
    const response = await client.chat(
      [{ role: 'user', content: context }],
      RESPONSE_SYSTEM_PROMPT,
    );
    // Discord message limit is 2000 chars
    return response.length > 1900 ? response.slice(0, 1900) + '...' : response;
  } catch (err) {
    console.error('[ClawPark Bot] LLM response error:', err);
    return 'Something went wrong generating a response. Please try again!';
  }
}

// --- Core message handler ---

async function handleBreedMessage(msg: Message, deps: DiscordBotDeps): Promise<void> {
  const { orchestratorDeps } = deps;
  const discordUserId = msg.author.id;
  const discordHandle = msg.author.tag;
  const userMessage = stripBotPrefix(msg.content);

  const requesterIdentity: RequesterIdentity = {
    discordUserId,
    discordHandle,
    anonymous: false,
  };

  const parsed = await parseDiscordMessage(msg.content);
  const breedable = orchestratorDeps.listBreedableSpecimens();
  const specimenContext = breedable.length > 0
    ? `Available specimens: ${breedable.map((s) => s.name).join(', ')} (${breedable.length} total)`
    : 'No specimens available yet. User needs to import OpenClaw ZIPs first.';

  // Extract mentioned users from raw message content
  const botId = msg.client.user?.id;
  console.log(`[ClawPark Bot] Raw content: "${msg.content}"`);
  // Match both user mentions <@id>/<@!id> AND role mentions <@&id>
  const allMentionMatches = [...msg.content.matchAll(/<@[!&]?(\d+)>/g)];
  const allMentionIds = allMentionMatches.map((m) => ({ id: m[1], isRole: m[0].includes('&') }));
  console.log(`[ClawPark Bot] All mentions: ${allMentionIds.map((m) => `${m.id}(${m.isRole ? 'role' : 'user'})`).join(', ') || 'none'}, botId: ${botId}`);
  // For role mentions, try to find guild members with that role
  const rawMentionIds: string[] = [];
  for (const mention of allMentionIds) {
    if (mention.id === botId) continue;
    if (mention.isRole && msg.guild) {
      // It's a role mention — find members with this role
      try {
        const role = msg.guild.roles.cache.get(mention.id);
        if (role) {
          const members = role.members;
          for (const [memberId] of members) {
            if (memberId !== botId) rawMentionIds.push(memberId);
          }
        }
      } catch { /* skip */ }
    } else {
      rawMentionIds.push(mention.id);
    }
  }
  const mentionedUsersList: MentionedUser[] = [];
  for (const id of rawMentionIds) {
    try {
      const user = await msg.client.users.fetch(id);
      if (user) mentionedUsersList.push({ id: user.id, displayName: user.displayName ?? user.username });
    } catch { /* skip unfetchable users */ }
  }
  console.log(`[ClawPark Bot] Mentions: ${mentionedUsersList.map((u) => `${u.displayName}(${u.id})`).join(', ') || 'none'}, botId=${botId}, rawIds=${rawMentionIds.join(',')}`);
  const mentionContext = mentionedUsersList.length > 0
    ? `\nMentioned users: ${mentionedUsersList.map((u) => `${u.displayName} (mention tag: <@${u.id}>)`).join(', ')}. IMPORTANT: When referring to these users in your response, use their Discord mention tag (e.g. <@${mentionedUsersList[0]?.id}>) so they get notified.`
    : '';
  if (isSpecimenInventoryQuestion(userMessage)) {
    await msg.reply(formatCandidateSuggestionsReply(
      breedable.map((specimen) => ({
        specimenId: specimen.id,
        name: specimen.name,
        compatibilitySummary: 'Available for breeding',
        eligibleForAutoApprove: specimen.ownerId === requesterIdentity.discordUserId || specimen.ownerId === null,
      })),
      'available-specimens',
    ));
    return;
  }

  const rememberedPersuadeTargets = getRememberedPersuadeTargets(discordUserId);
  const effectivePersuadeTargets = resolvePersuadeTargets(mentionedUsersList, rememberedPersuadeTargets, userMessage);

  // --- persuade: invite another user to upload their ZIP ---
  if (parsed.action === 'persuade' || effectivePersuadeTargets.length > 0 && isLikelyPersuadeFollowUp(userMessage)) {
    if (effectivePersuadeTargets.length > 0) {
      rememberPersuadeTargets(discordUserId, effectivePersuadeTargets);
      const targetMentions = effectivePersuadeTargets.map((u) => `<@${u.id}>`).join(', ');
      const targetNames = effectivePersuadeTargets.map((u) => u.displayName).join(', ');
      console.log(`[ClawPark Bot] Persuade intent for: ${targetNames}`);
      const response = await generateResponse(
        `User "${msg.author.displayName}" wants me to persuade ${targetNames} (Discord mentions: ${targetMentions}) to upload their OpenClaw agent ZIP to ClawPark for breeding.\n\nContext: ${specimenContext}\n\nWrite a fun, persuasive message DIRECTLY addressing the mentioned users using their mention tags (${targetMentions}). Make it exciting — talk about how their agent could breed with existing specimens, create unique children, track lineage. Be enthusiastic but not pushy. Tell them they can just drag-and-drop a ZIP file here and mention <@${botId}> to get started. Use <@${botId}> when referring to the bot, not "@ClawPark". Keep it under 150 words.`,
      );
      await msg.reply(response);
    } else {
      const response = await generateResponse(
        `User wants to persuade someone to upload, but didn't mention a specific user. Ask them to mention the user they want to invite, e.g. "@clawpark-demo persuade @username to upload their claw"`,
      );
      await msg.reply(response);
    }
    return;
  }

  // --- greet / unknown: pure LLM response ---
  if (parsed.action === 'greet' || parsed.action === 'unknown') {
    const response = await generateResponse(
      `User said: "${userMessage}"\n\nContext: ${specimenContext}${mentionContext}\n\nRespond naturally. If they mention other users, address those users directly using their Discord mention tags. If they're greeting, welcome them. If you can't understand their intent, ask them to clarify.`,
    );
    await msg.reply(response);
    return;
  }

  // --- Multi-turn: proceed / cancel ---
  if (parsed.action === 'proceed' || parsed.action === 'cancel') {
    const last = getUserLastIntent(discordUserId);
    if (!last) {
      const response = await generateResponse(
        `User said "${userMessage}" but there's no pending breeding action. ${specimenContext}. Suggest they start by finding a partner or naming two specimens to breed.`,
      );
      await msg.reply(response);
      return;
    }

    if (parsed.action === 'cancel') {
      cancelIntent(last.intentId, 'User cancelled');
      const response = await generateResponse(
        `User cancelled their pending breeding request. Confirm the cancellation and let them know they can start a new one anytime.`,
      );
      await msg.reply(response);
      return;
    }

    // proceed — advance last intent
    if (last.status === 'candidate_suggested') {
      if (last.targetSpecimenIds.length < 2 && last.suggestedCandidates.length > 0) {
        last.targetSpecimenIds.push(last.suggestedCandidates[0].specimenId);
      }

      const { intent, ready, blocked } = await checkEligibilityAndConsent(last.intentId, orchestratorDeps);
      if (!ready) {
        const statusContext = intent.status === 'consent_pending'
          ? 'Cross-owner breeding requires the other owner to approve. Request expires in 24 hours.'
          : `Breeding blocked: ${blocked}`;
        const response = await generateResponse(
          `User wants to proceed with breeding but it's blocked. Reason: ${statusContext}. Explain the situation.`,
        );
        await msg.reply(response);
        return;
      }

      const result = await executeBreed(last.intentId, orchestratorDeps);
      if (result.childName && result.lineageSummary) {
        markIntentSaved(last.intentId);
        const response = await generateResponse(
          `Breeding successful! A new specimen "${result.childName}" was born. Lineage: ${result.lineageSummary}. Announce the birth excitedly and mention the child has been saved to the nursery.`,
        );
        await msg.reply(response);
      }
      return;
    }

    if (last.status === 'eligibility_checked') {
      const result = await executeBreed(last.intentId, orchestratorDeps);
      if (result.childName && result.lineageSummary) {
        markIntentSaved(last.intentId);
        const response = await generateResponse(
          `Breeding successful! A new specimen "${result.childName}" was born. Lineage: ${result.lineageSummary}. Announce the birth excitedly.`,
        );
        await msg.reply(response);
      }
      return;
    }

    const response = await generateResponse(
      `User said "proceed" but there's nothing actionable pending (current status: ${last.status}). Suggest starting a new breed request. ${specimenContext}`,
    );
    await msg.reply(response);
    return;
  }

  // --- Resolve specimen names → IDs ---
  const targetSpecimenIds: string[] = [];
  for (const name of parsed.mentionedNames) {
    const found = orchestratorDeps.resolveSpecimenByName(name);
    if (found) targetSpecimenIds.push(found.id);
  }

  // --- Create intent ---
  const intent = createIntent({
    sourceSurface: 'discord_bot',
    sourceMessage: msg.content,
    requesterIdentity,
    parsedIntent: parsed,
    targetSpecimenIds,
  });
  setUserLastIntent(discordUserId, intent.intentId);

  // --- find_partner / compare: suggest candidates ---
  if (parsed.action === 'find_partner' || parsed.action === 'compare') {
    const updated = await suggestCandidates(intent.intentId, orchestratorDeps);
    if (updated.status === 'cancelled') {
      const response = await generateResponse(
        `User wants to find breeding partners but: ${updated.blockReason ?? 'No candidates found.'}. ${specimenContext}. Explain why and suggest what they can do.`,
      );
      await msg.reply(response);
      return;
    }
    const targetName = updated.targetSpecimenIds.length === 1
      ? orchestratorDeps.resolveSpecimenById(updated.targetSpecimenIds[0])?.name
      : undefined;
    await msg.reply(formatCandidateSuggestionsReply(
      updated.suggestedCandidates,
      updated.targetSpecimenIds.length === 1 ? 'partner-options' : 'available-specimens',
      targetName,
    ));
    return;
  }

  // --- breed: try to breed directly or suggest candidates ---
  if (parsed.action === 'breed') {
    if (targetSpecimenIds.length < 2) {
      const updated = await suggestCandidates(intent.intentId, orchestratorDeps);
      if (updated.status === 'cancelled' || updated.suggestedCandidates.length === 0) {
        const response = await generateResponse(
          `User wants to breed "${parsed.mentionedNames.join(', ')}" but couldn't find the specimens. ${specimenContext}. Help them identify the right specimens.`,
        );
        await msg.reply(response);
        return;
      }
      const foundNames = parsed.mentionedNames.filter((n) => orchestratorDeps.resolveSpecimenByName(n));
      const targetName = foundNames[0];
      await msg.reply(formatCandidateSuggestionsReply(
        updated.suggestedCandidates,
        foundNames.length === 1 ? 'partner-options' : 'available-specimens',
        targetName,
      ));
      return;
    }

    // Both specimens resolved — check eligibility and breed
    const { intent: checkedIntent, ready, blocked } = await checkEligibilityAndConsent(
      intent.intentId,
      orchestratorDeps,
    );
    if (!ready) {
      const parentNames = parsed.mentionedNames.join(' and ');
      const statusContext = checkedIntent.status === 'consent_pending'
        ? `Cross-owner breeding between ${parentNames} requires consent from the other owner. 24h timeout.`
        : `Cannot breed ${parentNames}: ${blocked}`;
      const response = await generateResponse(
        `Breeding blocked. ${statusContext}. Explain what the user needs to do next.`,
      );
      await msg.reply(response);
      return;
    }

    const result = await executeBreed(intent.intentId, orchestratorDeps);
    if (result.childName && result.lineageSummary) {
      markIntentSaved(intent.intentId);
      const response = await generateResponse(
        `Breeding successful! Parents: ${parsed.mentionedNames.join(' + ')}. Child: "${result.childName}". Lineage: ${result.lineageSummary}. Announce the birth! The child has been saved to the nursery.`,
      );
      await msg.reply(response);
    } else {
      const response = await generateResponse(
        `Breeding between ${parsed.mentionedNames.join(' and ')} failed unexpectedly. Apologize and suggest trying again.`,
      );
      await msg.reply(response);
    }
    return;
  }
}

// --- Bot factory ---

export function startDiscordBot(deps: DiscordBotDeps): Client {
  const client = new Client({
    intents: [
      GatewayIntentBits.Guilds,
      GatewayIntentBits.GuildMessages,
      GatewayIntentBits.MessageContent,
      GatewayIntentBits.DirectMessages,
    ],
  });

  client.once(Events.ClientReady, (c) => {
    console.log(`[ClawPark Bot] Ready as ${c.user.tag}`);
  });

  client.on(Events.MessageCreate, async (msg) => {
    // Allow other bots (OpenClaw agents) to interact — only skip our own messages
    if (msg.author.id === client.user?.id) return;

    const isMentioned = client.user !== null && msg.mentions.has(client.user);
    // Also check for role mentions that match the bot's name
    const hasRoleMention = msg.content.includes(`<@&`) && msg.mentions.roles.some((role) =>
      role.name.toLowerCase().includes('clawpark') || role.members.has(client.user?.id ?? ''),
    );
    const hasPrefix = msg.content.startsWith('!breed');
    const plainBotReference = containsPlainBotReference(msg.content, [
      client.user?.username ?? '',
      client.user?.displayName ?? '',
      msg.guild?.members.me?.displayName ?? '',
    ]);
    if (!isMentioned && !hasRoleMention && !hasPrefix && !plainBotReference) return;

    try {
      await msg.channel.sendTyping();

      // Handle ZIP file attachments
      const zipAttachment = msg.attachments.find((a) => a.name?.endsWith('.zip'));
      if (zipAttachment && deps.importSpecimen) {
        try {
          const tempDir = join(tmpdir(), `clawpark-discord-${randomUUID().slice(0, 8)}`);
          await mkdir(tempDir, { recursive: true });
          const tempPath = join(tempDir, zipAttachment.name ?? 'upload.zip');
          const response = await fetch(zipAttachment.url);
          const buffer = Buffer.from(await response.arrayBuffer());
          await writeFile(tempPath, buffer);
          const result = await deps.importSpecimen(tempPath, msg.author.id);
          await rm(tempDir, { recursive: true, force: true }).catch(() => {});
          const llmResponse = await generateResponse(
            `User "${msg.author.tag}" uploaded an OpenClaw ZIP file named "${zipAttachment.name}". It was successfully imported! Specimen name: "${result.specimenName}", ID: ${result.specimenId}. The specimen has been claimed and is ready to breed. Celebrate the import and suggest they can now breed it with other specimens or find partners.`,
          );
          await msg.reply(llmResponse);
          return;
        } catch (importErr) {
          const errMsg = importErr instanceof Error ? importErr.message : 'Unknown error';
          const llmResponse = await generateResponse(
            `User tried to upload a ZIP file "${zipAttachment.name}" but import failed: ${errMsg}. Explain what went wrong and remind them the ZIP must contain IDENTITY.md and SOUL.md files.`,
          );
          await msg.reply(llmResponse);
          return;
        }
      }

      const localZipPath = extractLocalZipPath(msg.content);
      if (localZipPath && deps.importSpecimen && deps.allowLocalZipPathImport) {
        try {
          if (!isAllowedLocalZipPath(localZipPath)) {
            throw new Error('Local ZIP path is outside the allowed dev import locations.');
          }
          const normalizedZipPath = normalizeLocalZipPath(localZipPath);
          await access(normalizedZipPath);
          const result = await deps.importSpecimen(normalizedZipPath, msg.author.id);
          const llmResponse = await generateResponse(
            `User "${msg.author.tag}" shared a local OpenClaw ZIP path "${normalizedZipPath}". It was successfully imported! Specimen name: "${result.specimenName}", ID: ${result.specimenId}. Celebrate the import and suggest they can now inspect or breed it.`,
          );
          await msg.reply(llmResponse);
          return;
        } catch (importErr) {
          const errMsg = importErr instanceof Error ? importErr.message : 'Unknown error';
          const llmResponse = await generateResponse(
            `User tried to hand off a local ZIP path "${localZipPath}" but import failed: ${errMsg}. Explain what went wrong. Mention that local-path imports are only supported in local development and the file must be a readable .zip under the allowed dev paths.`,
          );
          await msg.reply(llmResponse);
          return;
        }
      }

      await handleBreedMessage(msg, deps);
    } catch (error) {
      const errMsg = error instanceof Error ? error.message : 'Unknown error';
      console.error('[ClawPark Bot] Error:', error);
      try {
        const response = await generateResponse(
          `An error occurred while processing the user's request: ${errMsg}. Apologize briefly and suggest they try again.`,
        );
        await msg.reply(response);
      } catch {
        await msg.reply('Something went wrong. Please try again.').catch(() => {});
      }
    }
  });

  client.login(deps.token).catch((error: Error) => {
    console.error('[ClawPark Bot] Login failed:', error.message);
  });

  return client;
}
