// ClawPark Discord Coordinator Bot.
// All responses are generated by LLM (OpenRouter). No hardcoded user-facing messages.
// Trigger: @ClawPark mention OR !breed prefix.

import { Client, Events, GatewayIntentBits, type Message } from 'discord.js';
import type { OrchestratorDeps, RequesterIdentity } from '../src/types/breedingIntent.ts';
import { writeFile, mkdir, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';
import { parseDiscordMessage, stripBotPrefix } from './discordIntent.ts';
import { createOpenRouterClient } from './openrouter.ts';
import { parseOpenClawWorkspaceZip } from './openclawParser.ts';
import {
  cancelIntent,
  checkEligibilityAndConsent,
  createIntent,
  executeBreed,
  getUserLastIntent,
  markIntentSaved,
  setUserLastIntent,
  suggestCandidates,
} from './breedingOrchestrator.ts';

export interface DiscordBotDeps {
  token: string;
  orchestratorDeps: OrchestratorDeps;
  importSpecimen?: (zipPath: string, discordUserId: string) => Promise<{ specimenName: string; specimenId: string }>;
}

// --- LLM response generator ---

const RESPONSE_SYSTEM_PROMPT = `You are ClawPark Bot, a friendly Discord assistant for an OpenClaw agent breeding system.
You help users breed AI agents, discover breeding partners, and track lineage.

Rules:
- Be concise (1-3 short paragraphs max for Discord readability)
- Use Discord markdown (bold, code blocks, bullet points)
- Be warm and helpful, like a knowledgeable lab assistant
- If you have specimen data, mention names naturally
- Use emoji sparingly but appropriately
- Support both English and Korean naturally
- Never mention internal implementation details (API endpoints, JSON, etc.)
- When showing candidates, format as a numbered list with names`;

async function generateResponse(context: string): Promise<string> {
  try {
    const client = createOpenRouterClient();
    return await client.chat(
      [{ role: 'user', content: context }],
      RESPONSE_SYSTEM_PROMPT,
    );
  } catch {
    return context; // fallback to raw context if LLM fails
  }
}

// --- Core message handler ---

async function handleBreedMessage(msg: Message, deps: DiscordBotDeps): Promise<void> {
  const { orchestratorDeps } = deps;
  const discordUserId = msg.author.id;
  const discordHandle = msg.author.tag;
  const userMessage = stripBotPrefix(msg.content);

  const requesterIdentity: RequesterIdentity = {
    discordUserId,
    discordHandle,
    anonymous: false,
  };

  const parsed = await parseDiscordMessage(msg.content);
  const breedable = orchestratorDeps.listBreedableSpecimens();
  const specimenContext = breedable.length > 0
    ? `Available specimens: ${breedable.map((s) => s.name).join(', ')} (${breedable.length} total)`
    : 'No specimens available yet. User needs to import OpenClaw ZIPs first.';

  // Extract mentioned users (excluding the bot itself)
  const mentionedUsers = msg.mentions.users.filter((u) => u.id !== msg.client.user?.id);
  const mentionContext = mentionedUsers.size > 0
    ? `\nMentioned users: ${mentionedUsers.map((u) => `${u.displayName} (mention tag: <@${u.id}>)`).join(', ')}. IMPORTANT: When referring to these users in your response, use their Discord mention tag (e.g. <@${mentionedUsers.first()?.id}>) so they get notified.`
    : '';

  // --- persuade: invite another user to upload their ZIP ---
  if (parsed.action === 'persuade' && mentionedUsers.size > 0) {
    const targetMentions = mentionedUsers.map((u) => `<@${u.id}>`).join(', ');
    const targetNames = mentionedUsers.map((u) => u.displayName).join(', ');
    const response = await generateResponse(
      `User "${msg.author.displayName}" wants me to persuade ${targetNames} (Discord mentions: ${targetMentions}) to upload their OpenClaw agent ZIP to ClawPark for breeding.\n\nContext: ${specimenContext}\n\nWrite a fun, persuasive message DIRECTLY addressing the mentioned users using their mention tags (${targetMentions}). Make it exciting — talk about how their agent could breed with existing specimens, create unique children, track lineage. Be enthusiastic but not pushy. Tell them they can just drag-and-drop a ZIP file here and mention @ClawPark to get started. Keep it under 200 words.`,
    );
    await msg.reply(response);
    return;
  }

  // --- greet / unknown: pure LLM response ---
  if (parsed.action === 'greet' || parsed.action === 'unknown') {
    const response = await generateResponse(
      `User said: "${userMessage}"\n\nContext: ${specimenContext}${mentionContext}\n\nRespond naturally. If they mention other users, address those users directly using their Discord mention tags. If they're greeting, welcome them. If you can't understand their intent, ask them to clarify.`,
    );
    await msg.reply(response);
    return;
  }

  // --- Multi-turn: proceed / cancel ---
  if (parsed.action === 'proceed' || parsed.action === 'cancel') {
    const last = getUserLastIntent(discordUserId);
    if (!last) {
      const response = await generateResponse(
        `User said "${userMessage}" but there's no pending breeding action. ${specimenContext}. Suggest they start by finding a partner or naming two specimens to breed.`,
      );
      await msg.reply(response);
      return;
    }

    if (parsed.action === 'cancel') {
      cancelIntent(last.intentId, 'User cancelled');
      const response = await generateResponse(
        `User cancelled their pending breeding request. Confirm the cancellation and let them know they can start a new one anytime.`,
      );
      await msg.reply(response);
      return;
    }

    // proceed — advance last intent
    if (last.status === 'candidate_suggested') {
      if (last.targetSpecimenIds.length < 2 && last.suggestedCandidates.length > 0) {
        last.targetSpecimenIds.push(last.suggestedCandidates[0].specimenId);
      }

      const { intent, ready, blocked } = await checkEligibilityAndConsent(last.intentId, orchestratorDeps);
      if (!ready) {
        const statusContext = intent.status === 'consent_pending'
          ? 'Cross-owner breeding requires the other owner to approve. Request expires in 24 hours.'
          : `Breeding blocked: ${blocked}`;
        const response = await generateResponse(
          `User wants to proceed with breeding but it's blocked. Reason: ${statusContext}. Explain the situation.`,
        );
        await msg.reply(response);
        return;
      }

      const result = await executeBreed(last.intentId, orchestratorDeps);
      if (result.childName && result.lineageSummary) {
        markIntentSaved(last.intentId);
        const response = await generateResponse(
          `Breeding successful! A new specimen "${result.childName}" was born. Lineage: ${result.lineageSummary}. Announce the birth excitedly and mention the child has been saved to the nursery.`,
        );
        await msg.reply(response);
      }
      return;
    }

    if (last.status === 'eligibility_checked') {
      const result = await executeBreed(last.intentId, orchestratorDeps);
      if (result.childName && result.lineageSummary) {
        markIntentSaved(last.intentId);
        const response = await generateResponse(
          `Breeding successful! A new specimen "${result.childName}" was born. Lineage: ${result.lineageSummary}. Announce the birth excitedly.`,
        );
        await msg.reply(response);
      }
      return;
    }

    const response = await generateResponse(
      `User said "proceed" but there's nothing actionable pending (current status: ${last.status}). Suggest starting a new breed request. ${specimenContext}`,
    );
    await msg.reply(response);
    return;
  }

  // --- Resolve specimen names → IDs ---
  const targetSpecimenIds: string[] = [];
  for (const name of parsed.mentionedNames) {
    const found = orchestratorDeps.resolveSpecimenByName(name);
    if (found) targetSpecimenIds.push(found.id);
  }

  // --- Create intent ---
  const intent = createIntent({
    sourceSurface: 'discord_bot',
    sourceMessage: msg.content,
    requesterIdentity,
    parsedIntent: parsed,
    targetSpecimenIds,
  });
  setUserLastIntent(discordUserId, intent.intentId);

  // --- find_partner / compare: suggest candidates ---
  if (parsed.action === 'find_partner' || parsed.action === 'compare') {
    const updated = await suggestCandidates(intent.intentId, orchestratorDeps);
    if (updated.status === 'cancelled') {
      const response = await generateResponse(
        `User wants to find breeding partners but: ${updated.blockReason ?? 'No candidates found.'}. ${specimenContext}. Explain why and suggest what they can do.`,
      );
      await msg.reply(response);
      return;
    }
    const candidateInfo = updated.suggestedCandidates
      .map((c, i) => `${i + 1}. ${c.name} — ${c.compatibilitySummary} (auto-approve: ${c.eligibleForAutoApprove})`)
      .join('\n');
    const response = await generateResponse(
      `User asked to find breeding partners. Here are the candidates:\n${candidateInfo}\n\nPresent these as breeding options. Tell the user they can say "proceed" to breed with the first option, or name a specific specimen.`,
    );
    await msg.reply(response);
    return;
  }

  // --- breed: try to breed directly or suggest candidates ---
  if (parsed.action === 'breed') {
    if (targetSpecimenIds.length < 2) {
      const updated = await suggestCandidates(intent.intentId, orchestratorDeps);
      if (updated.status === 'cancelled' || updated.suggestedCandidates.length === 0) {
        const response = await generateResponse(
          `User wants to breed "${parsed.mentionedNames.join(', ')}" but couldn't find the specimens. ${specimenContext}. Help them identify the right specimens.`,
        );
        await msg.reply(response);
        return;
      }
      const candidateInfo = updated.suggestedCandidates
        .map((c, i) => `${i + 1}. ${c.name} — ${c.compatibilitySummary}`)
        .join('\n');
      const foundNames = parsed.mentionedNames.filter((n) => orchestratorDeps.resolveSpecimenByName(n));
      const response = await generateResponse(
        `User wants to breed but only found ${foundNames.length} of ${parsed.mentionedNames.length} specimens (found: ${foundNames.join(', ') || 'none'}). Here are available candidates:\n${candidateInfo}\n\nSuggest they pick a partner or say "proceed" for #1.`,
      );
      await msg.reply(response);
      return;
    }

    // Both specimens resolved — check eligibility and breed
    const { intent: checkedIntent, ready, blocked } = await checkEligibilityAndConsent(
      intent.intentId,
      orchestratorDeps,
    );
    if (!ready) {
      const parentNames = parsed.mentionedNames.join(' and ');
      const statusContext = checkedIntent.status === 'consent_pending'
        ? `Cross-owner breeding between ${parentNames} requires consent from the other owner. 24h timeout.`
        : `Cannot breed ${parentNames}: ${blocked}`;
      const response = await generateResponse(
        `Breeding blocked. ${statusContext}. Explain what the user needs to do next.`,
      );
      await msg.reply(response);
      return;
    }

    const result = await executeBreed(intent.intentId, orchestratorDeps);
    if (result.childName && result.lineageSummary) {
      markIntentSaved(intent.intentId);
      const response = await generateResponse(
        `Breeding successful! Parents: ${parsed.mentionedNames.join(' + ')}. Child: "${result.childName}". Lineage: ${result.lineageSummary}. Announce the birth! The child has been saved to the nursery.`,
      );
      await msg.reply(response);
    } else {
      const response = await generateResponse(
        `Breeding between ${parsed.mentionedNames.join(' and ')} failed unexpectedly. Apologize and suggest trying again.`,
      );
      await msg.reply(response);
    }
    return;
  }
}

// --- Bot factory ---

export function startDiscordBot(deps: DiscordBotDeps): Client {
  const client = new Client({
    intents: [
      GatewayIntentBits.Guilds,
      GatewayIntentBits.GuildMessages,
      GatewayIntentBits.MessageContent,
      GatewayIntentBits.DirectMessages,
    ],
  });

  client.once(Events.ClientReady, (c) => {
    console.log(`[ClawPark Bot] Ready as ${c.user.tag}`);
  });

  client.on(Events.MessageCreate, async (msg) => {
    if (msg.author.bot) return;

    const isMentioned = client.user !== null && msg.mentions.has(client.user);
    const hasPrefix = msg.content.startsWith('!breed');
    if (!isMentioned && !hasPrefix) return;

    try {
      await msg.channel.sendTyping();

      // Handle ZIP file attachments
      const zipAttachment = msg.attachments.find((a) => a.name?.endsWith('.zip'));
      if (zipAttachment && deps.importSpecimen) {
        try {
          const tempDir = join(tmpdir(), `clawpark-discord-${randomUUID().slice(0, 8)}`);
          await mkdir(tempDir, { recursive: true });
          const tempPath = join(tempDir, zipAttachment.name ?? 'upload.zip');
          const response = await fetch(zipAttachment.url);
          const buffer = Buffer.from(await response.arrayBuffer());
          await writeFile(tempPath, buffer);
          const result = await deps.importSpecimen(tempPath, msg.author.id);
          await rm(tempDir, { recursive: true, force: true }).catch(() => {});
          const llmResponse = await generateResponse(
            `User "${msg.author.tag}" uploaded an OpenClaw ZIP file named "${zipAttachment.name}". It was successfully imported! Specimen name: "${result.specimenName}", ID: ${result.specimenId}. The specimen has been claimed and is ready to breed. Celebrate the import and suggest they can now breed it with other specimens or find partners.`,
          );
          await msg.reply(llmResponse);
          return;
        } catch (importErr) {
          const errMsg = importErr instanceof Error ? importErr.message : 'Unknown error';
          const llmResponse = await generateResponse(
            `User tried to upload a ZIP file "${zipAttachment.name}" but import failed: ${errMsg}. Explain what went wrong and remind them the ZIP must contain IDENTITY.md and SOUL.md files.`,
          );
          await msg.reply(llmResponse);
          return;
        }
      }

      await handleBreedMessage(msg, deps);
    } catch (error) {
      const errMsg = error instanceof Error ? error.message : 'Unknown error';
      console.error('[ClawPark Bot] Error:', error);
      try {
        const response = await generateResponse(
          `An error occurred while processing the user's request: ${errMsg}. Apologize briefly and suggest they try again.`,
        );
        await msg.reply(response);
      } catch {
        await msg.reply('Something went wrong. Please try again.').catch(() => {});
      }
    }
  });

  client.login(deps.token).catch((error: Error) => {
    console.error('[ClawPark Bot] Login failed:', error.message);
  });

  return client;
}
